import { type Metadata } from "next";

import { Urbanist } from "next/font/google";
import "../globals.css";
import Sidebar from "@/components/Sidebar";
import DashboardNavbar from "@/components/Dashboard/DashboardNavbar";

const urbanist = Urbanist({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-urbanist",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div lang="en" className="flex w-full">
      <Sidebar />
      <div className="flex-1 ml-5 mt-2">{children}</div>
    </div>
  );
}
